url:  
baseurl: 

# Site settings
title: Case Départ
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

prose:
  rooturl: ''
  siteurl: 'https://casedepart-ludotheque.github.io/'
  ignore:
    - 404.html
    - lib
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
    - /_plugins
    - /_site
    - /css
    - /font
    - /img
    - /js
    - /mail
    - index.html
    - style.css
    - .prose.yml
    - gemfile
    - gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - favicon.png
    - feed.xml
  media: 'img/posts'
  metadata:
    _posts:
      - name: "titre"
        field:
          label: "Titre de l'article"
          element: "text"
          placeholder: "Titre"
      - name: "datepost"
        field:
          label: "Date de publication"
          element: "text"
          placeholder: "Jour N° Mois"
      - name: "lieu"
        field:
          label: "Lieu"
          element: "text"
          placeholder: "Entrer le lieu"
      - name: "category"
        field:
          label: "Catégorie"
          element: "select"
          options:
            - Agenda
            - Nouveautés
            - Évènements extérieurs
      - name: "excerpt"
        field:
          label: "Text court"
          element: "text"
          placeholder: "Entrer un texte résumé (1 phrase ou 2)"
      - name: "description"
        field:
          label: "Description complète"
          element: "textarea"
          placeholder: "Entrer la descrition complete"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "hidden"
          placeholder: "YYYY-MM-DD"
          value: CURRENT_DATETIME










